---
{"dg-publish":true,"dg-path":"Python/第07章-异常处理.md","permalink":"/Python/第07章-异常处理/"}
---

# 一、Bug的由来及分类
**Bug**指的是检测并排除计算机程序/机器中的故障
## Bug的常见类型
1. 粗心导致的语法错误
	1. 漏了末尾的冒号，如if语句、循环语句、else子句等
	2. 缩进错误，该缩进的没有缩进，不该缩进的乱缩进
	3. 把英文符号写成中文符号，例如：引号、冒号、括号
	4. 字符串拼接的时候，把字符串和数字拼在一起
	5. 没有定义变量，例如：while循环条件的变量没有定义
	6. “\=\=”比较运算符和“\=”赋值运算符的混用
2. 知识点掌握不熟练
3. 思路不清导致的问题
	- 解决思路不清导致的问题的思路有两种：
		1. 第一种是使用printO函数
		2. 第二种是使用“#”暂时注释部分代码
4. 由于用户输入操作导致的程序崩溃
	- 解决方案：使用异常处理机制
# 二、Python中的异常处理
## 1.try...except
**try...except的语法结构为：**
```python
try:
	可能会抛出异常的代码
except 异常类型:
	异常处理代码（报错后执行的代码）
```
**try...except...except的语法结构为：**
```python
try:
	可能会抛出异常的代码
except 异常类型A:
	异常处理代码（报错后执行的代码）
except 异常类型B:
	异常处理代码（报错后执行的代码）
```
注意：捕获异常是有个顺序的，它会按照先子类再父类的顺序，子类和父类在后面的章节会讲。在此处，这个except可以写多个，最大的异常类型写在最后，就能捕获最多的异常类型，叫作BaseException。

**try...except...else的语法结构为：**
```python
try:
	可能会抛出异常的代码
except 异常类型:
	异常处理代码（报错后执行的代码）
else:
	没有抛异常要执行的代码
```
**try...except...else...finally的语法结构为：**
```python
try:
	可能会抛出异常的代码
except 异常类型:
	异常处理代码（报错后执行的代码）
else:
	没有抛异常要执行的代码
finally:
	无论是否产生异常都要执行的代码
```
> [!note]- 举例
> ```python
> try:
>     num1 = int(input('请输入一个整数:'))
>     num2 = int(input('请输入另一个整数:'))
>     result = num1 / num2
> except ZeroDivisionError:
>     print('除数不能为0')
> except ValueError:
>     print('不能将字符串转成整数')
> except BaseException:
>     print('未知异常')
> else:
>     print('结果:', result)
> finally:
>     print('程序执行结束！')
> ```
## 2.raise关键字的使用
作用：抛出一个异常，从而提醒程序出现了异常情况，程序能够正确地处理这些异常情况

**raise关键字的语法结构为：**
```python
raise [Exception类型(异常描述信息)]
```
举例：
```python
try:
    gender=input('请输入您的性别:')
    if gender!='男' and gender!='女':
        raise Exception('性别只能是男或女')
    else:
        print('您的性别是:',gender)
except Exception as e: # 给这个异常对象起个名字e
    print(e)
```
## 3.Python中常见的异常类型
|异常类型|描述说明|
|:-:|:-:|
|ZeroDivisionError|当除数为0时，引发的异常|
|IndexError|索引超出范围所引发的异常|
|KeyError|字典取值时key不存在的异常|
|NameError|使用一个没有声明的变量时引发的异常|
|SyntaxError|Python中的语法错误|
|ValueError|传入的值错误|
|AttributeError|属性或方法不存在的异常|
|TypeError|类型不合适引发的异常|
|IndentationError|不正确的缩进引发的异常|

## 4.PyCharm的程序调试
**使用PyCharm进行代码调试的操作步骤：**
1. 设置断点
2. 进入调试视图
	- 进入调试视图有三种方式
		1. 单击工具栏上的调试按钮
		2. 右键单击编辑区：点击“Debug模块名”
		3. 快捷键：Shift+F9
3. 开始调试
	- 几个窗口
		1. 变量查看窗口
		2. 调试控制窗口
		3. 线程控制窗口
		4. 程序控制窗口

几个调试窗口：
![../../../Extras/Media/media-第07章-异常处理-1.png|7-2几个调试窗口](/img/user/Extras/Media/media-%E7%AC%AC07%E7%AB%A0-%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86-1.png)
调试控制窗口介绍：
![../../../Extras/Media/media-第07章-异常处理-2.png|7-3调试控制窗口介绍](/img/user/Extras/Media/media-%E7%AC%AC07%E7%AB%A0-%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86-2.png)
程序控制窗口介绍：
![../../../Extras/Media/media-第07章-异常处理-3.png|7-1程序控制窗口介绍](/img/user/Extras/Media/media-%E7%AC%AC07%E7%AB%A0-%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86-3.png)
**PyCharm调试的步骤：**
1. 设置断点
	- 通常是设在函数的定义处，然后是循环处
2. 单步运行
3. 观察变量
4. 查找问题
5. 重新调试，直至问题解决
# 章节习题
1. 在使用try-except语句捕获异常时，如果在except后面不指定异常名称，则表示：
A．随机捕获异常
B．捕获指定异常
C．捕获全部异常
D．不捕获异常

> [!note]- 答案
> 答案：C

2. 如果分配了有限的资源，则应将释放这些资源的代码放置在（ ）代码块中。
A．finally
B．except
C．else
D．def

> [!note]- 答案
> 答案：A
> 解析：
> 因为finally当中，是无论是否产生异常都要执行的代码。

***
# 参考文献
[1] 杨淑娟.花了2万多买的Python教程全套，现在分享给大家，入门到精通(Python全栈开发教程)\_哔哩哔哩\_bilibili\[EB/OL\].\[2025-09-14\].[花了2万多买的Python教程全套，现在分享给大家，入门到精通(Python全栈开发教程)_哔哩哔哩_bilibili](https://www.bilibili.com/video/BV1wD4y1o7AS/)